#!/bin/sh

# Script to manage the aesdsocket daemon
DAEMON=/usr/bin/aesdsocket
DAEMON_NAME=aesdsocket
DAEMON_OPTS="-d"
PIDFILE=/var/run/$DAEMON_NAME.pid

case "$1" in
    start)
        echo "Starting $DAEMON_NAME"
        start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        ;;
    stop)
        echo "Stopping $DAEMON_NAME"
        start-stop-daemon --stop --pidfile $PIDFILE --signal SIGTERM
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    status)
        if [ -f $PIDFILE ]; then
            PID=$(cat $PIDFILE)
            if ps -p $PID > /dev/null; then
                echo "$DAEMON_NAME is running with PID $PID"
                exit 0
            else
                echo "$DAEMON_NAME is not running, but PID file exists"
                exit 1
            fi
        else
            echo "$DAEMON_NAME is not running"
            exit 3
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
